name: Trigger auto deployment for aca-remindme-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/aca-remindme-bot-AutoDeployTrigger-a5320a74-6a5f-4713-b6e5-39044ff158eb.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.ACAREMINDMEBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.ACAREMINDMEBOT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: btron/remindmebot:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAREMINDMEBOT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aca-remindme-bot -g rg-remindme-bot --server docker.io --username  ${{ secrets.ACAREMINDMEBOT_REGISTRY_USERNAME }} --password ${{ secrets.ACAREMINDMEBOT_REGISTRY_PASSWORD }}
            az containerapp update -n aca-remindme-bot -g rg-remindme-bot --image btron/remindmebot:${{ github.sha }}
